import { Elysia } from "elysia";
import cors from "@elysiajs/cors";
import JSZip from "jszip";
import { writeFileSync, mkdirSync } from "fs";

// In-memory store for last generated site
let lastSite: Record<string, string> = {};

const groq = async (prompt: string, system?: string) => {
  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${process.env.GROQ_API_KEY}`
    },
    body: JSON.stringify({
      model: "llama-3.3-70b-versatile",
      messages: [
        ...(system ? [{ role: "system", content: system }] : []),
        { role: "user", content: prompt }
      ],
      max_tokens: 4096
    })
  });
  const data = await res.json();
  return data.choices?.[0]?.message?.content || "";
};

const app = new Elysia()
  .use(cors())

  .get("/", () => ({
    status: "HERMES AI ONLINE",
    runtime: "bun",
    version: "2.0",
    services: ["ai", "generator", "preview", "zip-download"]
  }))

  .post("/api/ai", async ({ body }) => {
    const { input } = body as any;
    try {
      const output = await groq(input);
      return { output };
    } catch {
      return { output: "Groq unavailable" };
    }
  })

  .post("/api/generate", async ({ body }) => {
    const { prompt } = body as any;
    const system = `You are an expert web developer.
Generate a complete, beautiful, modern website based on the user prompt.
Respond ONLY with a JSON object (no markdown, no backticks, no extra text):
{"projectName":"slug-name","files":{"index.html":"full html here","style.css":"full css here","app.js":"full js here"}}
Make the HTML fully self-contained with the CSS and JS inlined if needed.`;

    try {
      const raw = await groq(prompt, system);
      const clean = raw.replace(/```json|```/g, "").trim();
      const parsed = JSON.parse(clean);
      // Store for preview
      lastSite = parsed.files || {};
      return {
        ...parsed,
        previewUrl: "https://davteam-backend-bun.onrender.com/preview"
      };
    } catch {
      const fallback = {
        "index.html": `<!DOCTYPE html><html><head><title>${prompt}</title><style>body{background:#000;color:#00ffcc;font-family:monospace;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;}.box{text-align:center;border:1px solid #00ffcc;padding:40px;border-radius:8px;}</style></head><body><div class="box"><h1>${prompt}</h1><p>Generated by Hermes AI</p></div></body></html>`,
        "style.css": "body{background:#000;color:#00ffcc;}",
        "app.js": `console.log("${prompt}");`
      };
      lastSite = fallback;
      return {
        projectName: "hermes-fallback",
        files: fallback,
        previewUrl: "https://davteam-backend-bun.onrender.com/preview"
      };
    }
  })

  // Serve preview as real HTML page
  .get("/preview", ({ set }) => {
    set.headers["Content-Type"] = "text/html";
    if (!lastSite["index.html"]) {
      return `<!DOCTYPE html><html><body style="background:#000;color:#00ffcc;font-family:monospace;text-align:center;padding:40px"><h2>No site generated yet.</h2><p>Run 'gen' command first.</p></body></html>`;
    }
    // Inject CSS and JS inline for self-contained preview
    let html = lastSite["index.html"];
    if (lastSite["style.css"] && !html.includes("<style>")) {
      html = html.replace("</head>", `<style>${lastSite["style.css"]}</style></head>`);
    }
    if (lastSite["app.js"] && !html.includes("<script>")) {
      html = html.replace("</body>", `<script>${lastSite["app.js"]}</script></body>`);
    }
    return html;
  })

  .post("/api/download", async ({ body }) => {
    const { files } = body as any;
    const zip = new JSZip();
    for (const [name, content] of Object.entries(files)) {
      zip.file(name, content as string);
    }
    const buffer = await zip.generateAsync({ type: "nodebuffer" });
    writeFileSync("./generated.zip", buffer);
    return { download: "./generated.zip" };
  })

  .listen(Number(process.env.PORT) || 10000);

console.log("[HERMES READY] :10000");
